version: "3.9"

services:
  db:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_blog
    ports:
      - "5432:5432"

  backend:
    build: src/be/
    container_name: backend
    environment:
      ALLOW_CORS_ORIGIN: http://localhost:3000
      JWT_SECRET_KEY: fSKaeKuj6sgFMYdcwL06qdXiJZ6I57rJ
      DATABASE_URL: postgres://postgres:password@db:5432/simple_blog
    depends_on:
      - db
    command: >
      sh -c "
        bunx prisma migrate deploy &&
        bunx prisma db seed &&
        bun run start
      "
    ports:
      - "8080:8080"

  frontend:
    build: src/fe/
    container_name: frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
    ports:
      - "3000:3000"

